### ISSUE TITLE
multiple times with clocks

### ISSUE THREAD

**Issue by fossfreedom** [samlane-ma/analogue-clock-applet#3]
Suggestion for a future enhancement?

With the ability to have multiple clocks on various panels - maybe have the ability to vary the time shown?  e.g. show the time of New York & Tokyo as well as your local time?

This might be through a UTC type dropdown timezone maybe? or drop-down of major capitals?  might be complicated where some countries are UTC +/- hour & 30 minutes rather than a whole hour.

**Comment by samlane-ma** [comment]
Definitely something I will add.  UTC drop down at the least seems like it shouldn't be too hard.

With this I should probably also add the timezone / UTC+/- information to the popover, or to mouse hover tooltip.  Or possibly the ability set a name that appears instead.

**Comment by samlane-ma** [comment]
Thank you for suggestions.  Made a few enhancements:
- Each clock can now show a different time besides local by selecting a UTC+/- from a drop-down
- The clock will show "Local Time", or show the UTC time zone (if selected) in both the popover and tooltip
- Each clock can optionally be named, so the name will appear instead of showing "Local Time" or timezone name
- Gtk.Calendar in popover selects the correct day based on each clock's timezone, instead of always the current day in local time
- minor tweaks to improve appearance on Ubuntu Budgie default theme and Solus built-in theme, at default panel sizes

Of course, suggestions / criticisms on any of these changes are appreciated
